# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            UR Machine Learning Blog
tagline:          'A blog about data science and machine learning'
description:      'Data Scientist at City of Edmonton'
url:              https://usmanr149.github.io
baseurl:          '/urmlblog'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
linkedin:
  url:         https://www.linkedin.com/in/usman-rizwan-data-magic/

github:
  url:            https://github.com/usmanr149/

author:
  name:           'Usman Rizwan'
  url:            https://github.com/usmanr149

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

disqus:
  shortname: https-usmanr149-github-io-urmlblog

google_analytics: 'UA-162541860-1'